IO_NIO_HW
DanilaBeket0W/nix_12_Danila pull request #8
Opened 2022-08-05 10:02 UTC by DanilaBeket0W

2022-08-05 10:03 UTC, DanilaBeket0W commented
![](https://github.trello.services/images/mini-trello-icon.png) [IO/NIO](https://trello.com/c/hDOXFp0L/91-io-nio)

2022-08-05 20:59 UTC, Fabolo12 requested changes

2022-08-05 20:59 UTC, Fabolo12 commented on src/main/java/ua/cars/commands/IO_NIO_Comand.java
> +        System.out.println("readJSONFile: " + readFile(JSON_PATTERN,"src/main/resources/car.json"));
Чтение файла неверное

2022-08-05 20:59 UTC, Fabolo12 commented on target/classes/car.json
> +[
А почему папка таргет в гит попала

2022-08-05 20:59 UTC, Fabolo12 commented on src/main/resources/car.xml
> +    <price>1500</price>
Ты сильно упростил себе задачу убрав отсюда валюту из средины тега

2022-08-13 11:37 UTC, Fabolo12 approved these changes

2022-08-15 08:15 UTC, merged